drop table if exists "user", genre, rating, film, film_genre, "like", friendship;

create table "user" (
	user_id int generated by default as identity primary key,
	email varchar(100) not null unique,
	login varchar(100) not null unique,
	name varchar(100) not null,
	birthday date
);
create table genre (
	genre_id int generated by default as identity primary key,
	name varchar(50) not null
);
create table rating (
	rating_id int generated by default as identity primary key,
	name varchar(50)
);
create table film (
	film_id int generated by default as identity primary key,
	name varchar(200) not null,
	description varchar(200),
	release_date date,
	duration bigint check(duration > 1),
	rating_id int not null references rating (rating_id) on delete restrict
);

create table film_genre (
	film_id int not null references film (film_id) on delete cascade,
	genre_id int not null references genre (genre_id) on delete cascade,
	primary key (film_id, genre_id)
);

create table "like" (
	film_id int not null references film (film_id) on delete cascade,
	user_id int not null references "user" (user_id) on delete cascade,
	primary key (film_id, user_id)
);

create table friendship (
	user_id int not null references "user" (user_id) on delete cascade,
	friend_id int not null references "user" (user_id) on delete cascade,
	friendship_status bool not null,
	primary key (user_id, friend_id)
);
